# Meridian - Omakase Ruby styling + RSpec extensions
inherit_gem:
  rubocop-rails-omakase: rubocop.yml

plugins:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "db/migrate/*"
    - "node_modules/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "storage/**/*"
    - "config/initializers/devise.rb"

# House style overrides
Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "config/routes.rb"
    - "config/environments/*"

# RSpec
RSpec/ExampleLength:
  Max: 15
RSpec/MultipleExpectations:
  Max: 5
RSpec/NestedGroups:
  Max: 5
